# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.18.6" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.18.6.tgz";
        sha512 = "TDCmlK5eOvH+eH7cdAFlNXeVJqWIQ7gW9tY1GJIpUtFb6CmjVyq2VM3u71bOyR8CRihcCgMUYoDNyLXao3+70Q==";
      };
    };
    "@babel/helper-validator-identifier-7.18.6" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.18.6.tgz";
        sha512 = "MmetCkz9ej86nJQV+sFCxoGGrUbU3q02kgLciwkrt9QqEB7cP39oKEY0PakknEO0Gu20SskMRi+AYZ3b1TpN9g==";
      };
    };
    "@babel/highlight-7.18.6" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.18.6.tgz";
        sha512 = "u7stbOuYjaPezCuLj29hNW1v64M2Md2qupEKP1fHc7WdOA3DgLh37suiSrZYY7haUB7iBeQZ9P1uiRF359do3g==";
      };
    };
    "@frida/assert-3.0.2" = {
      name = "_at_frida_slash_assert";
      packageName = "@frida/assert";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/assert/-/assert-3.0.2.tgz";
        sha512 = "JXJq5SbXGrM5EkjrZKfRmB29zOoEOix02NC6A5TSJ+C1GE/X051EinJJsuOO2pEOx7KZwpvAHvS0WXW0+levKg==";
      };
    };
    "@frida/base64-js-2.0.3" = {
      name = "_at_frida_slash_base64-js";
      packageName = "@frida/base64-js";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/base64-js/-/base64-js-2.0.3.tgz";
        sha512 = "2w0F+1TynOTCZ/v7du9LdHPWwq0lJhazjo2fF9upMyQmA1zHetT14fLuQ1v/6T0qPgyeEGkiSrybstU8EsgeUA==";
      };
    };
    "@frida/buffer-7.0.4" = {
      name = "_at_frida_slash_buffer";
      packageName = "@frida/buffer";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/buffer/-/buffer-7.0.4.tgz";
        sha512 = "RxQ1lZRRiCJj7nhcCiD8xeJx0NsLpGGnjqsmTg7jShGmbnVFMN5W7+J+3gqdPSQhc/IxNBIWc6zRXVp4+qnYHg==";
      };
    };
    "@frida/crosspath-3.0.0" = {
      name = "_at_frida_slash_crosspath";
      packageName = "@frida/crosspath";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/crosspath/-/crosspath-3.0.0.tgz";
        sha512 = "bNdO1spIPD2P40XtK89N49oZpJhstdlnkJZcD4yJ17jrdkm9Ctu0sd9MIEX6Z8Tm8ydhVJBAOMEKl9/R27onAQ==";
      };
    };
    "@frida/diagnostics_channel-1.0.0" = {
      name = "_at_frida_slash_diagnostics_channel";
      packageName = "@frida/diagnostics_channel";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/diagnostics_channel/-/diagnostics_channel-1.0.0.tgz";
        sha512 = "mYX1jp/5Bpk24tHArJNx65iCk7qSuV8YJkdU0gFNVtJUXxfV8BG5WuPa4mL+ynxsbWWpsg/cwKZbLAepYKTdQQ==";
      };
    };
    "@frida/events-4.0.4" = {
      name = "_at_frida_slash_events";
      packageName = "@frida/events";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/events/-/events-4.0.4.tgz";
        sha512 = "qJVQ6VWHf9sjUKuiJzoCAC00frbpcwxeYfvQ+PP9LU/d70j+QvjWgYe98Qa3ekLaBU6r/AvWm8ThKCDUCLWrQQ==";
      };
    };
    "@frida/http-4.0.2" = {
      name = "_at_frida_slash_http";
      packageName = "@frida/http";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/http/-/http-4.0.2.tgz";
        sha512 = "cvkc7ex7GmVXVOWqtjXKBWUUbYEBgpNRKZbEEoMeI8KiIs8zejKwg+N7rx7296Ao+EP3+xcUr4wBVr3xLaUVfQ==";
      };
    };
    "@frida/http-parser-js-1.0.0" = {
      name = "_at_frida_slash_http-parser-js";
      packageName = "@frida/http-parser-js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/http-parser-js/-/http-parser-js-1.0.0.tgz";
        sha512 = "2nMrNXt/OeTlWbqnE8AH4Sfz4I2+BGoN206dzKEyC/g2svtn83Xu+zuv/V3TkwrA27s26Mcy84ZwsXeNlqNxUQ==";
      };
    };
    "@frida/https-1.0.0" = {
      name = "_at_frida_slash_https";
      packageName = "@frida/https";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/https/-/https-1.0.0.tgz";
        sha512 = "OiqQ6qsALcWOktRLq07oJ0i6sH8eX6MXb/MdZS1qVKDRf6wchH4Pjn6fiLB+pt/OlYbggk+DOfpHwSdjTwuHMQ==";
      };
    };
    "@frida/ieee754-2.0.2" = {
      name = "_at_frida_slash_ieee754";
      packageName = "@frida/ieee754";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/ieee754/-/ieee754-2.0.2.tgz";
        sha512 = "wlcUebnne4ENN7GDr5pTH598ZDLMVOsh0FjenxeVOe6u7ewZkz9gGRnLnZKJAm9kl5G6XhdxhI0cSXVQK/rQUw==";
      };
    };
    "@frida/net-4.0.1" = {
      name = "_at_frida_slash_net";
      packageName = "@frida/net";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/net/-/net-4.0.1.tgz";
        sha512 = "lmzg7LMjjWluu2RqE4PSe5QpgYEbCWjL08twsOLcYnhMz95jWmxY35A0PBySrEw1ulaflsMvXwsONnhl5bk6AQ==";
      };
    };
    "@frida/os-1.0.2" = {
      name = "_at_frida_slash_os";
      packageName = "@frida/os";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/os/-/os-1.0.2.tgz";
        sha512 = "3ISAiGNiyIya3QN2EHBCz1wqP0enTdSxP99wUeroeh8+AQRmgoOr/5TRnrVry8pe378anay3fmV/tdUMMSkehQ==";
      };
    };
    "@frida/path-2.0.3" = {
      name = "_at_frida_slash_path";
      packageName = "@frida/path";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/path/-/path-2.0.3.tgz";
        sha512 = "2RQy36QatoC846fzBhBhV8sXMsSOBGoYvwTHeaE1zUdz7F4RNScP4QEekTTooBYWYX/XjiF36KQpYAzc9OYFtg==";
      };
    };
    "@frida/process-1.2.1" = {
      name = "_at_frida_slash_process";
      packageName = "@frida/process";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/process/-/process-1.2.1.tgz";
        sha512 = "nvCu22DstFW2ttGFtOKekHM7vnjbZm+XgtvavOt427GNT6uV7k0JYK9tnMbcLMRWv57DG6udAmuJlWs8Paq1ag==";
      };
    };
    "@frida/punycode-3.0.0" = {
      name = "_at_frida_slash_punycode";
      packageName = "@frida/punycode";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/punycode/-/punycode-3.0.0.tgz";
        sha512 = "XVSDY2KamDs1D5/fTVgHcOSNxdU4kTboxzqJMBbTjcQC7XScIT9c0EfbwKCq7Kci6gWQdsHSCr7lU+9Oc4KAdg==";
      };
    };
    "@frida/querystring-1.0.0" = {
      name = "_at_frida_slash_querystring";
      packageName = "@frida/querystring";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/querystring/-/querystring-1.0.0.tgz";
        sha512 = "15m1fOZPmoO/vWlgPJrG/J9/BJDz6a2/JpVGpS8ynNzo+fBhTznaStX5nHxUs24mVTqh/OqLo0EiYJM5WWHXxg==";
      };
    };
    "@frida/readable-stream-4.1.3" = {
      name = "_at_frida_slash_readable-stream";
      packageName = "@frida/readable-stream";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/readable-stream/-/readable-stream-4.1.3.tgz";
        sha512 = "ntGUFmi+CryRGRJIK13a/VST2Ad19uivbln8Xd92vKPAARq+6vMIASDyZIqyl5BLRccfiyCHdYgrgQ6RI5rUig==";
      };
    };
    "@frida/reserved-words-1.0.0" = {
      name = "_at_frida_slash_reserved-words";
      packageName = "@frida/reserved-words";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/reserved-words/-/reserved-words-1.0.0.tgz";
        sha512 = "2yG/XxJlsGlk/mm6eZTb4OAaQEhkTI2qaFfZFtAsrA/XuCpuMWkS4y/guyBlsRu4hAuhK2HPmNM8+OLLK1zM9Q==";
      };
    };
    "@frida/rollup-plugin-node-polyfills-1.0.3" = {
      name = "_at_frida_slash_rollup-plugin-node-polyfills";
      packageName = "@frida/rollup-plugin-node-polyfills";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/rollup-plugin-node-polyfills/-/rollup-plugin-node-polyfills-1.0.3.tgz";
        sha512 = "n5bvqpND25gbeYGnKH15Kt098tTN9RimD1WKCiqY4JVi62FwQ15bmOgCp95AwtxjlcsYSRhQeMcWoEcYIJqP2A==";
      };
    };
    "@frida/stream-1.0.2" = {
      name = "_at_frida_slash_stream";
      packageName = "@frida/stream";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/stream/-/stream-1.0.2.tgz";
        sha512 = "4OuaC1ztmEKgTq3WeBhsy8Oq+AwW9n9cYnvLklcC9jwD93AEwgbWpecLlxJCVuALvTMdhKPg0nQVfyGYP/i9Bw==";
      };
    };
    "@frida/string_decoder-2.0.0" = {
      name = "_at_frida_slash_string_decoder";
      packageName = "@frida/string_decoder";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/string_decoder/-/string_decoder-2.0.0.tgz";
        sha512 = "in371tYZMHQiW9HF5MS3JDw6Ao6tyBoq34UWy2rzOswYyMG1rpizh85ofi/yVkxDiaqybEZefxzkVittpPGT6g==";
      };
    };
    "@frida/terser-1.0.0" = {
      name = "_at_frida_slash_terser";
      packageName = "@frida/terser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/terser/-/terser-1.0.0.tgz";
        sha512 = "59h9WuNzD1Rx/zwoWqQ/FW/4Y/Q3R91Eng2hEwdHapqiTDvtKbZ08F6CynCR7ZVinrh4tLYsF46AtVPTz1ys9g==";
      };
    };
    "@frida/timers-3.0.0" = {
      name = "_at_frida_slash_timers";
      packageName = "@frida/timers";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/timers/-/timers-3.0.0.tgz";
        sha512 = "3b+0igv10aT8TMxefrTAd06rActqbxJLY2Xkkq9vYcPBffB/yHszl0NYIp/5ko8WC3ecDYPU6bQiY6fjs72zTA==";
      };
    };
    "@frida/tty-1.0.0" = {
      name = "_at_frida_slash_tty";
      packageName = "@frida/tty";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/tty/-/tty-1.0.0.tgz";
        sha512 = "p/kjLnKYxEAB1MdYP8+5rKv9CsHzyA+0jg9BcGETzjQVKHHcroHDULRxDYUh+DC7qs6cpX8QdDQh9E+a6ydgsQ==";
      };
    };
    "@frida/url-1.0.2" = {
      name = "_at_frida_slash_url";
      packageName = "@frida/url";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/url/-/url-1.0.2.tgz";
        sha512 = "ZKunbKJHMr8w2Eb/5K1avy0MzK1B998S17wYXNv3RmzBGxMm8S5T0F3qEpRxkU7/72P8m4izyQU87fWl+FjQsQ==";
      };
    };
    "@frida/util-1.0.3" = {
      name = "_at_frida_slash_util";
      packageName = "@frida/util";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/util/-/util-1.0.3.tgz";
        sha512 = "htcG3uDiRXv89ERVNNYhfase39kJ2X75ZARfrYcYEtJLFEsSk0nemM1YnEIR4CjrHvdvkWHrwgKkS+acOyoNEg==";
      };
    };
    "@frida/vm-2.0.0" = {
      name = "_at_frida_slash_vm";
      packageName = "@frida/vm";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/vm/-/vm-2.0.0.tgz";
        sha512 = "7fsjLWscZT5odNIBtg6qbLNI+vAk1xmii6H5W2kaYkMYt0vRohQEcDSUWacA+eaWlu5SvMjZI82Yibj/3G9pJw==";
      };
    };
    "@jridgewell/gen-mapping-0.3.2" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.2.tgz";
        sha512 = "mh65xKQAzI6iBcFzwv28KVWSmCkdRBWoOh+bYQGW3+6OZvbbN3TqMGo5hqYxQniRcH9F2VZIoJCm4pa3BPDK/A==";
      };
    };
    "@jridgewell/resolve-uri-3.1.0" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.0.tgz";
        sha512 = "F2msla3tad+Mfht5cJq7LSXcdudKTWCVYUgw6pLFOOHSTtZlj6SWNYAp+AhuqLmWdBO2X5hPrLcu8cVP8fy28w==";
      };
    };
    "@jridgewell/set-array-1.1.2" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.1.2.tgz";
        sha512 = "xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==";
      };
    };
    "@jridgewell/source-map-0.3.2" = {
      name = "_at_jridgewell_slash_source-map";
      packageName = "@jridgewell/source-map";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/source-map/-/source-map-0.3.2.tgz";
        sha512 = "m7O9o2uR8k2ObDysZYzdfhb08VuEml5oWGiosa1VdaPZ/A6QyPkAJuwN0Q1lhULOf6B7MtQmHENS743hWtCrgw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.14" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.14.tgz";
        sha512 = "XPSJHWmi394fuUuzDnGz1wiKqWfo1yXecHQMRf2l6hztTO+nPru658AyDngaBe7isIxEkRsPR3FZh+s7iVa4Uw==";
      };
    };
    "@jridgewell/trace-mapping-0.3.15" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.15.tgz";
        sha512 = "oWZNOULl+UbhsgB51uuZzglikfIKSUBO/M9W2OfEjn7cmqoAiCgmv9lyACTUacZwBz0ITnJ2NqjU8Tx0DHL88g==";
      };
    };
    "@rollup/plugin-inject-4.0.4" = {
      name = "_at_rollup_slash_plugin-inject";
      packageName = "@rollup/plugin-inject";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-inject/-/plugin-inject-4.0.4.tgz";
        sha512 = "4pbcU4J/nS+zuHk+c+OL3WtmEQhqxlZ9uqfjQMQDOHOPld7PsCd8k5LWs8h5wjwJN7MgnAn768F2sDxEP4eNFQ==";
      };
    };
    "@rollup/plugin-node-resolve-14.1.0" = {
      name = "_at_rollup_slash_plugin-node-resolve";
      packageName = "@rollup/plugin-node-resolve";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-node-resolve/-/plugin-node-resolve-14.1.0.tgz";
        sha512 = "5G2niJroNCz/1zqwXtk0t9+twOSDlG00k1Wfd7bkbbXmwg8H8dvgHdIWAun53Ps/rckfvOC7scDBjuGFg5OaWw==";
      };
    };
    "@rollup/plugin-replace-4.0.0" = {
      name = "_at_rollup_slash_plugin-replace";
      packageName = "@rollup/plugin-replace";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-replace/-/plugin-replace-4.0.0.tgz";
        sha512 = "+rumQFiaNac9y64OHtkHGmdjm7us9bo1PlbgQfdihQtuNxzjpaB064HbRnewUOggLQxVCCyINfStkgmBeQpv1g==";
      };
    };
    "@rollup/plugin-typescript-8.5.0" = {
      name = "_at_rollup_slash_plugin-typescript";
      packageName = "@rollup/plugin-typescript";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-typescript/-/plugin-typescript-8.5.0.tgz";
        sha512 = "wMv1/scv0m/rXx21wD2IsBbJFba8wGF3ErJIr6IKRfRj49S85Lszbxb4DCo8iILpluTjk2GAAu9CoZt4G3ppgQ==";
      };
    };
    "@rollup/pluginutils-3.1.0" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-3.1.0.tgz";
        sha512 = "GksZ6pr6TpIjHm8h9lSQ8pi8BE9VeubNT0OMJ3B5uZJ8pz73NPiqOtCog/x2/QzM1ENChPKxMDhiQuRHsqc+lg==";
      };
    };
    "@types/estree-0.0.39" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.39.tgz";
        sha512 = "EYNwp3bU+98cpU4lAWYYL7Zz+2gryWH1qbdDTidVd6hkiR6weksdbMadyXKXNPEkQFhXM+hVO9ZygomHXp+AIw==";
      };
    };
    "@types/frida-gum-18.2.0" = {
      name = "_at_types_slash_frida-gum";
      packageName = "@types/frida-gum";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/frida-gum/-/frida-gum-18.2.0.tgz";
        sha512 = "bCaM57vIj33IKMSSrYp5VHjxUAH5SC65wmtOqdABemP/uepcPYQvaujusb4lzwX3lFjLP9nNlGIEcTlCP4SXgA==";
      };
    };
    "@types/glob-8.0.0" = {
      name = "_at_types_slash_glob";
      packageName = "@types/glob";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/glob/-/glob-8.0.0.tgz";
        sha512 = "l6NQsDDyQUVeoTynNpC9uRvCUint/gSUXQA2euwmTuWGvPY5LSDUu6tkCtJB2SvGQlJQzLaKqcGZP4//7EDveA==";
      };
    };
    "@types/minimatch-5.1.2" = {
      name = "_at_types_slash_minimatch";
      packageName = "@types/minimatch";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/minimatch/-/minimatch-5.1.2.tgz";
        sha512 = "K0VQKziLUWkVKiRVrx4a40iPaxTUefQmjtkQofBkYRcoaaL/8rhwDWww9qWbrgicNOgnpIsMxyNIUM4+n6dUIA==";
      };
    };
    "@types/node-17.0.45" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.45.tgz";
        sha512 = "w+tIMs3rq2afQdsPJlODhoUEKzFP1ayaoyl1CcnwtIlsVe7K7bA1NGm4s3PraqTLlXnbIN84zuBlxBWo1u9BLw==";
      };
    };
    "@types/node-18.7.23" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.7.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.7.23.tgz";
        sha512 = "DWNcCHolDq0ZKGizjx2DZjR/PqsYwAcYUJmfMWqtVU2MBMG5Mo+xFZrhGId5r/O5HOuMPyQEcM6KUBp5lBZZBg==";
      };
    };
    "@types/resolve-1.17.1" = {
      name = "_at_types_slash_resolve";
      packageName = "@types/resolve";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/resolve/-/resolve-1.17.1.tgz";
        sha512 = "yy7HuzQhj0dhGpD8RLXSZWEkLsV9ibvxvi6EiJ3bkqLAO1RGo0WbkWQiwpRlSFymTJRz0d3k5LM3kkx8ArDbLw==";
      };
    };
    "acorn-8.8.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.8.0.tgz";
        sha512 = "QOxyigPVrpZ2GXT+PFyZTl6TtOFc5egxHIP9IlQ+RbupQuX4RkT/Bee4/kQuC02Xkzg84JcT7oLYtDIQxp+v7w==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "builtin-modules-3.3.0" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-3.3.0.tgz";
        sha512 = "zhaCDicdLuWN5UbN5IMnFqNMhNfo919sH85y2/ea+5Yg9TsTkeZxpL+JLbp6cgYFS4sRLp3YV4S6yDuqVWHYOw==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-9.4.0" = {
      name = "commander";
      packageName = "commander";
      version = "9.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-9.4.0.tgz";
        sha512 = "sRPT+umqkz90UA8M1yqYfnHlZA7fF6nSphDtxeywPZ49ysjxDQybzk13CL+mXekDRG92skbcqCLVovuCusNmFw==";
      };
    };
    "deepmerge-4.2.2" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.2.2.tgz";
        sha512 = "FJ3UgI4gIl+PHZm53knsuSFpE+nESMr7M4v9QcgB7S63Kj/6WqMiFQJpBBYz1Pt+66bZpP3Q7Lye0Oo9MPKEdg==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "estree-walker-1.0.1" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-1.0.1.tgz";
        sha512 = "1fMXF3YP4pZZVozF8j/ZLfvnR8NSIljt56UhbZ5PeeDmmGHpgpdwQt7ITlGvYaQukCvuBRMLEiKiYC+oeIg4cg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "frida-compile-16.1.4" = {
      name = "frida-compile";
      packageName = "frida-compile";
      version = "16.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/frida-compile/-/frida-compile-16.1.4.tgz";
        sha512 = "e8bO2qsHm81gXXxelWDoA6uqIaZxiKTGLHjkyCFfq55J52rWv8G02tZ7G4B0NLGmz5FKmkyEXRXh2idzQ71smA==";
      };
    };
    "frida-fs-5.2.1" = {
      name = "frida-fs";
      packageName = "frida-fs";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/frida-fs/-/frida-fs-5.2.1.tgz";
        sha512 = "2trmxZ4PHOXNr73PAExGoZ+UN6mcQHusDv+YT4bM4PbT/F/g9zClbmN3Aq2cZUDwDfh0cPtXq5ZTcpnD6fxDeg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "glob-8.0.3" = {
      name = "glob";
      packageName = "glob";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-8.0.3.tgz";
        sha512 = "ull455NHSHI/Y1FqGaaYFaLGkNMMJbavMrEGFXG/PGrg6y7sutWHUHrz6gy6WEBH6akM1M414dWKCNs+IhKdiQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "http-parser-js-0.5.8" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.8.tgz";
        sha512 = "SGeBX54F94Wgu5RH3X5jsDtf4eHyRogWX1XGT3b4HuW3tQPM4AaBzoUji/4AAJNXCEOWZ5O0DgZmJw1947gD5Q==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-builtin-module-3.2.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-3.2.0.tgz";
        sha512 = "phDA4oSGt7vl1n5tJvTWooWWAsXLY+2xCnxNqvKhGEzujg+A43wPlPOyDg3C8XQHN+6k/JTQWJ/j0dQh/qr+Hw==";
      };
    };
    "is-core-module-2.10.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.10.0.tgz";
        sha512 = "Erxj2n/LDAZ7H8WNJXd9tw38GYM3dv8rk8Zcs+jJuxYTW7sozH+SS8NtrSjVL1/vpLvWi1hxy96IzjJ3EHTJJg==";
      };
    };
    "is-module-1.0.0" = {
      name = "is-module";
      packageName = "is-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-module/-/is-module-1.0.0.tgz";
        sha512 = "51ypPSPCoTEIN9dy5Oy+h4pShgJmPCygKfyRCISBI+JoWT/2oJvK8QPxmwv7b/p239jXrm9M1mlQbyKJ5A152g==";
      };
    };
    "jest-worker-26.6.2" = {
      name = "jest-worker";
      packageName = "jest-worker";
      version = "26.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jest-worker/-/jest-worker-26.6.2.tgz";
        sha512 = "KWYVV1c4i+jbMpaBC+U++4Va0cp8OisU185o73T1vo99hqi7w8tSJfUXYswwqqrjzwxa6KpRK54WhPvwf5w6PQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "magic-string-0.25.9" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.9.tgz";
        sha512 = "RmF0AsMzgt25qzqqLc1+MbHmhdx0ojF2Fvs4XnOqz2ZOBXzzkEwc/dJQZCYHAn7v1jbVOjAZfK8msRn4BxO4VQ==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "minimatch-5.1.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-5.1.0.tgz";
        sha512 = "9TPBGGak4nHfGZsPBohm9AWg6NoT7QTCehS3BIJABslyZbzxfV78QM2Y6+i741OPZIafFAaiiEMh5OyIrJPgtg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "rollup-2.79.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.79.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.79.1.tgz";
        sha512 = "uKxbd0IhMZOhjAiD5oAFp7BqvkA4Dv47qpOCtaNvng4HBwdbWtdOh8f5nZNuk2rp51PMGk3bzfWu5oayNEuYnw==";
      };
    };
    "rollup-plugin-terser-7.0.2" = {
      name = "rollup-plugin-terser";
      packageName = "rollup-plugin-terser";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-plugin-terser/-/rollup-plugin-terser-7.0.2.tgz";
        sha512 = "w3iIaU4OxcF52UUXiZNsNeuXIMDvFrr+ZXK6bFZ0Q60qyVfq4uLptoS4bbq3paG3x216eQllFZX7zt6TIImguQ==";
      };
    };
    "rxjs-7.5.6" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.5.6.tgz";
        sha512 = "dnyv2/YsXhnm461G+R/Pe5bWP41Nm6LBXEYWI6eiFP4fiwx6WRI/CD0zbdVAudd9xwLEF2IDcKXLHit0FYjUzw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "serialize-javascript-4.0.0" = {
      name = "serialize-javascript";
      packageName = "serialize-javascript";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-javascript/-/serialize-javascript-4.0.0.tgz";
        sha512 = "GaNA54380uFefWghODBWEGisLZFj00nS5ACs6yHa9nLqlLpVLO8ChDGeKRjZnV4Nh4n0Qi7nhYZD/9fCPzEqkw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "terser-5.15.0" = {
      name = "terser";
      packageName = "terser";
      version = "5.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.15.0.tgz";
        sha512 = "L1BJiXVmheAQQy+as0oF3Pwtlo4s3Wi1X2zNZ2NxOB4wx9bdS9Vk67XQENLFdLYGCK/Z2di53mTj/hBafR+dTA==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "typed-emitter-2.1.0" = {
      name = "typed-emitter";
      packageName = "typed-emitter";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-emitter/-/typed-emitter-2.1.0.tgz";
        sha512 = "g/KzbYKbH5C2vPkaXGu8DJlHrGKHLsM25Zg9WuC9pMGfuvT+X25tZQWo5fK1BjBm8+UrVE9LDCvaY0CQk+fXDA==";
      };
    };
    "typescript-4.8.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.8.2.tgz";
        sha512 = "C0I1UsrrDHo2fYI5oaCGbSejwX4ch+9Y5jTQELvovfmFkK3HHSZJB8MSJcWLmCUBzQBchCrZ9rMRV6GuNrvGtw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
  };
  args = {
    name = "frida-compiler-agent";
    packageName = "frida-compiler-agent";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@babel/code-frame-7.18.6"
      sources."@babel/helper-validator-identifier-7.18.6"
      sources."@babel/highlight-7.18.6"
      sources."@frida/assert-3.0.2"
      sources."@frida/base64-js-2.0.3"
      sources."@frida/buffer-7.0.4"
      (sources."@frida/crosspath-3.0.0" // {
        dependencies = [
          sources."@types/node-17.0.45"
        ];
      })
      sources."@frida/diagnostics_channel-1.0.0"
      sources."@frida/events-4.0.4"
      sources."@frida/http-4.0.2"
      sources."@frida/http-parser-js-1.0.0"
      sources."@frida/https-1.0.0"
      sources."@frida/ieee754-2.0.2"
      sources."@frida/net-4.0.1"
      sources."@frida/os-1.0.2"
      sources."@frida/path-2.0.3"
      sources."@frida/process-1.2.1"
      sources."@frida/punycode-3.0.0"
      sources."@frida/querystring-1.0.0"
      sources."@frida/readable-stream-4.1.3"
      sources."@frida/reserved-words-1.0.0"
      sources."@frida/rollup-plugin-node-polyfills-1.0.3"
      sources."@frida/stream-1.0.2"
      sources."@frida/string_decoder-2.0.0"
      (sources."@frida/terser-1.0.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."@frida/timers-3.0.0"
      sources."@frida/tty-1.0.0"
      sources."@frida/url-1.0.2"
      sources."@frida/util-1.0.3"
      sources."@frida/vm-2.0.0"
      sources."@jridgewell/gen-mapping-0.3.2"
      sources."@jridgewell/resolve-uri-3.1.0"
      sources."@jridgewell/set-array-1.1.2"
      sources."@jridgewell/source-map-0.3.2"
      sources."@jridgewell/sourcemap-codec-1.4.14"
      sources."@jridgewell/trace-mapping-0.3.15"
      sources."@rollup/plugin-inject-4.0.4"
      sources."@rollup/plugin-node-resolve-14.1.0"
      sources."@rollup/plugin-replace-4.0.0"
      sources."@rollup/plugin-typescript-8.5.0"
      (sources."@rollup/pluginutils-3.1.0" // {
        dependencies = [
          sources."estree-walker-1.0.1"
        ];
      })
      sources."@types/estree-0.0.39"
      sources."@types/frida-gum-18.2.0"
      sources."@types/glob-8.0.0"
      sources."@types/minimatch-5.1.2"
      sources."@types/node-18.7.23"
      sources."@types/resolve-1.17.1"
      sources."acorn-8.8.0"
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."brace-expansion-2.0.1"
      sources."buffer-from-1.1.2"
      sources."builtin-modules-3.3.0"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-9.4.0"
      sources."deepmerge-4.2.2"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."frida-compile-16.1.4"
      sources."frida-fs-5.2.1"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."glob-8.0.3"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."http-parser-js-0.5.8"
      sources."ieee754-1.2.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-builtin-module-3.2.0"
      sources."is-core-module-2.10.0"
      sources."is-module-1.0.0"
      (sources."jest-worker-26.6.2" // {
        dependencies = [
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."js-tokens-4.0.0"
      sources."magic-string-0.25.9"
      sources."merge-stream-2.0.0"
      sources."minimatch-5.1.0"
      sources."once-1.4.0"
      sources."path-parse-1.0.7"
      sources."picomatch-2.3.1"
      sources."randombytes-2.1.0"
      sources."resolve-1.22.1"
      sources."rollup-2.79.1"
      sources."rollup-plugin-terser-7.0.2"
      sources."rxjs-7.5.6"
      sources."safe-buffer-5.2.1"
      sources."serialize-javascript-4.0.0"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.21"
      sources."sourcemap-codec-1.4.8"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      (sources."terser-5.15.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."tslib-2.4.0"
      sources."typed-emitter-2.1.0"
      sources."typescript-4.8.2"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Agent used by Frida's compiler";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
