# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@frida/assert-3.0.2" = {
      name = "_at_frida_slash_assert";
      packageName = "@frida/assert";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/assert/-/assert-3.0.2.tgz";
        sha512 = "JXJq5SbXGrM5EkjrZKfRmB29zOoEOix02NC6A5TSJ+C1GE/X051EinJJsuOO2pEOx7KZwpvAHvS0WXW0+levKg==";
      };
    };
    "@frida/base64-js-2.0.3" = {
      name = "_at_frida_slash_base64-js";
      packageName = "@frida/base64-js";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/base64-js/-/base64-js-2.0.3.tgz";
        sha512 = "2w0F+1TynOTCZ/v7du9LdHPWwq0lJhazjo2fF9upMyQmA1zHetT14fLuQ1v/6T0qPgyeEGkiSrybstU8EsgeUA==";
      };
    };
    "@frida/buffer-7.0.4" = {
      name = "_at_frida_slash_buffer";
      packageName = "@frida/buffer";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/buffer/-/buffer-7.0.4.tgz";
        sha512 = "RxQ1lZRRiCJj7nhcCiD8xeJx0NsLpGGnjqsmTg7jShGmbnVFMN5W7+J+3gqdPSQhc/IxNBIWc6zRXVp4+qnYHg==";
      };
    };
    "@frida/diagnostics_channel-1.0.0" = {
      name = "_at_frida_slash_diagnostics_channel";
      packageName = "@frida/diagnostics_channel";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/diagnostics_channel/-/diagnostics_channel-1.0.0.tgz";
        sha512 = "mYX1jp/5Bpk24tHArJNx65iCk7qSuV8YJkdU0gFNVtJUXxfV8BG5WuPa4mL+ynxsbWWpsg/cwKZbLAepYKTdQQ==";
      };
    };
    "@frida/events-4.0.3" = {
      name = "_at_frida_slash_events";
      packageName = "@frida/events";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/events/-/events-4.0.3.tgz";
        sha512 = "TMB0tPe4jMQTj/RLr9lMyj6Xr2J+6xNySTBV+S2Y0NrB8/SwtT6HJaZmQlxJyTVWHAcj+UzSwCUEu8eK+rltEg==";
      };
    };
    "@frida/http-4.0.1" = {
      name = "_at_frida_slash_http";
      packageName = "@frida/http";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/http/-/http-4.0.1.tgz";
        sha512 = "fQioTV9lPcgGniVjZX2sKfCXuzlka0cw/jqJs/HA1I3P/sRKVc9gS5W/DJVBHgL3EXfqmLWu3dw0k2KD/g0nZg==";
      };
    };
    "@frida/http-parser-js-1.0.0" = {
      name = "_at_frida_slash_http-parser-js";
      packageName = "@frida/http-parser-js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/http-parser-js/-/http-parser-js-1.0.0.tgz";
        sha512 = "2nMrNXt/OeTlWbqnE8AH4Sfz4I2+BGoN206dzKEyC/g2svtn83Xu+zuv/V3TkwrA27s26Mcy84ZwsXeNlqNxUQ==";
      };
    };
    "@frida/https-1.0.0" = {
      name = "_at_frida_slash_https";
      packageName = "@frida/https";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/https/-/https-1.0.0.tgz";
        sha512 = "OiqQ6qsALcWOktRLq07oJ0i6sH8eX6MXb/MdZS1qVKDRf6wchH4Pjn6fiLB+pt/OlYbggk+DOfpHwSdjTwuHMQ==";
      };
    };
    "@frida/ieee754-2.0.2" = {
      name = "_at_frida_slash_ieee754";
      packageName = "@frida/ieee754";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/ieee754/-/ieee754-2.0.2.tgz";
        sha512 = "wlcUebnne4ENN7GDr5pTH598ZDLMVOsh0FjenxeVOe6u7ewZkz9gGRnLnZKJAm9kl5G6XhdxhI0cSXVQK/rQUw==";
      };
    };
    "@frida/net-4.0.0" = {
      name = "_at_frida_slash_net";
      packageName = "@frida/net";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/net/-/net-4.0.0.tgz";
        sha512 = "U6spRrvRM2M7zOYsXe05QID22DHxfTnliBA8p8P2Gzvr0dErDfggK4ut/eMjTcUh/2nPwljJ6pEVZHfbE4nWMQ==";
      };
    };
    "@frida/os-1.0.2" = {
      name = "_at_frida_slash_os";
      packageName = "@frida/os";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/os/-/os-1.0.2.tgz";
        sha512 = "3ISAiGNiyIya3QN2EHBCz1wqP0enTdSxP99wUeroeh8+AQRmgoOr/5TRnrVry8pe378anay3fmV/tdUMMSkehQ==";
      };
    };
    "@frida/path-2.0.2" = {
      name = "_at_frida_slash_path";
      packageName = "@frida/path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/path/-/path-2.0.2.tgz";
        sha512 = "QF4USKvaGWYvKisyvAH4x5arVj5F71n4enFLR/4xH0ZYoIsQwim7CCWg4bU9v0DKw8iPjHEwkCnkP4bm6L5IKA==";
      };
    };
    "@frida/process-1.1.1" = {
      name = "_at_frida_slash_process";
      packageName = "@frida/process";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/process/-/process-1.1.1.tgz";
        sha512 = "jnTiGdNG1QSmb0a7RgPrlBHsj6lirGeAIjF3Rb/bfdjy3xbjkMlqUfq/6/Tjw+DaQ+p4eN2z7arftHT59hM5hA==";
      };
    };
    "@frida/punycode-3.0.0" = {
      name = "_at_frida_slash_punycode";
      packageName = "@frida/punycode";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/punycode/-/punycode-3.0.0.tgz";
        sha512 = "XVSDY2KamDs1D5/fTVgHcOSNxdU4kTboxzqJMBbTjcQC7XScIT9c0EfbwKCq7Kci6gWQdsHSCr7lU+9Oc4KAdg==";
      };
    };
    "@frida/querystring-1.0.0" = {
      name = "_at_frida_slash_querystring";
      packageName = "@frida/querystring";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/querystring/-/querystring-1.0.0.tgz";
        sha512 = "15m1fOZPmoO/vWlgPJrG/J9/BJDz6a2/JpVGpS8ynNzo+fBhTznaStX5nHxUs24mVTqh/OqLo0EiYJM5WWHXxg==";
      };
    };
    "@frida/readable-stream-4.1.3" = {
      name = "_at_frida_slash_readable-stream";
      packageName = "@frida/readable-stream";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/readable-stream/-/readable-stream-4.1.3.tgz";
        sha512 = "ntGUFmi+CryRGRJIK13a/VST2Ad19uivbln8Xd92vKPAARq+6vMIASDyZIqyl5BLRccfiyCHdYgrgQ6RI5rUig==";
      };
    };
    "@frida/stream-1.0.1" = {
      name = "_at_frida_slash_stream";
      packageName = "@frida/stream";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/stream/-/stream-1.0.1.tgz";
        sha512 = "iqmnkhfoDcMjPcn0I6J0jz67L05zCB7by1FNq39UiM3VCBzm7JLaZTDDmMOGXYqwCETmrBcHvP+02v32QFXO3w==";
      };
    };
    "@frida/string_decoder-2.0.0" = {
      name = "_at_frida_slash_string_decoder";
      packageName = "@frida/string_decoder";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/string_decoder/-/string_decoder-2.0.0.tgz";
        sha512 = "in371tYZMHQiW9HF5MS3JDw6Ao6tyBoq34UWy2rzOswYyMG1rpizh85ofi/yVkxDiaqybEZefxzkVittpPGT6g==";
      };
    };
    "@frida/timers-3.0.0" = {
      name = "_at_frida_slash_timers";
      packageName = "@frida/timers";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/timers/-/timers-3.0.0.tgz";
        sha512 = "3b+0igv10aT8TMxefrTAd06rActqbxJLY2Xkkq9vYcPBffB/yHszl0NYIp/5ko8WC3ecDYPU6bQiY6fjs72zTA==";
      };
    };
    "@frida/tty-1.0.0" = {
      name = "_at_frida_slash_tty";
      packageName = "@frida/tty";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/tty/-/tty-1.0.0.tgz";
        sha512 = "p/kjLnKYxEAB1MdYP8+5rKv9CsHzyA+0jg9BcGETzjQVKHHcroHDULRxDYUh+DC7qs6cpX8QdDQh9E+a6ydgsQ==";
      };
    };
    "@frida/url-1.0.1" = {
      name = "_at_frida_slash_url";
      packageName = "@frida/url";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/url/-/url-1.0.1.tgz";
        sha512 = "c1gp4HnH9Cv+KCmTmXTJicBFtTcjAVZUDkQ7bY1o+A1mz82EeIJD9eTqeDtwGOA1RNVj2F2odZ+/Dyo5cpVhxA==";
      };
    };
    "@frida/util-1.0.3" = {
      name = "_at_frida_slash_util";
      packageName = "@frida/util";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/util/-/util-1.0.3.tgz";
        sha512 = "htcG3uDiRXv89ERVNNYhfase39kJ2X75ZARfrYcYEtJLFEsSk0nemM1YnEIR4CjrHvdvkWHrwgKkS+acOyoNEg==";
      };
    };
    "@frida/vm-2.0.0" = {
      name = "_at_frida_slash_vm";
      packageName = "@frida/vm";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@frida/vm/-/vm-2.0.0.tgz";
        sha512 = "7fsjLWscZT5odNIBtg6qbLNI+vAk1xmii6H5W2kaYkMYt0vRohQEcDSUWacA+eaWlu5SvMjZI82Yibj/3G9pJw==";
      };
    };
    "@jridgewell/gen-mapping-0.3.2" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.2.tgz";
        sha512 = "mh65xKQAzI6iBcFzwv28KVWSmCkdRBWoOh+bYQGW3+6OZvbbN3TqMGo5hqYxQniRcH9F2VZIoJCm4pa3BPDK/A==";
      };
    };
    "@jridgewell/resolve-uri-3.0.8" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.0.8.tgz";
        sha512 = "YK5G9LaddzGbcucK4c8h5tWFmMPBvRZ/uyWmN1/SbBdIvqGUdWGkJ5BAaccgs6XbzVLsqbPJrBSFwKv3kT9i7w==";
      };
    };
    "@jridgewell/set-array-1.1.2" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.1.2.tgz";
        sha512 = "xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==";
      };
    };
    "@jridgewell/source-map-0.3.2" = {
      name = "_at_jridgewell_slash_source-map";
      packageName = "@jridgewell/source-map";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/source-map/-/source-map-0.3.2.tgz";
        sha512 = "m7O9o2uR8k2ObDysZYzdfhb08VuEml5oWGiosa1VdaPZ/A6QyPkAJuwN0Q1lhULOf6B7MtQmHENS743hWtCrgw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.14" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.14.tgz";
        sha512 = "XPSJHWmi394fuUuzDnGz1wiKqWfo1yXecHQMRf2l6hztTO+nPru658AyDngaBe7isIxEkRsPR3FZh+s7iVa4Uw==";
      };
    };
    "@jridgewell/trace-mapping-0.3.14" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.14.tgz";
        sha512 = "bJWEfQ9lPTvm3SneWwRFVLzrh6nhjwqw7TUFFBEMzwvg7t7PCDenf2lDwqo4NQXzdpgBXyFgDWnQA+2vkruksQ==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@types/frida-gum-18.0.0" = {
      name = "_at_types_slash_frida-gum";
      packageName = "@types/frida-gum";
      version = "18.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/frida-gum/-/frida-gum-18.0.0.tgz";
        sha512 = "WomBKqhdkk7CSNDCu9saraHYe0eH/iszea+vTRNVk1kin5fSzLGSwZYX7R3zvObxyaHreMctcDwByGxhTOgy6A==";
      };
    };
    "@types/node-17.0.45" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.45.tgz";
        sha512 = "w+tIMs3rq2afQdsPJlODhoUEKzFP1ayaoyl1CcnwtIlsVe7K7bA1NGm4s3PraqTLlXnbIN84zuBlxBWo1u9BLw==";
      };
    };
    "acorn-8.7.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.7.1.tgz";
        sha512 = "Xx54uLJQZ19lKygFXOWsscKUbsBZW0CPykPhVQdhIeIwrbPmJzqeASDInc8nKBnp/JT6igTs82qPXz069H8I/A==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-9.3.0" = {
      name = "commander";
      packageName = "commander";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-9.3.0.tgz";
        sha512 = "hv95iU5uXPbK83mjrJKuZyFM/LBAoCV/XhVGkS5Je6tl7sxr6A0ITMw5WoRV46/UaJ46Nllm3Xt7IaJhXTIkzw==";
      };
    };
    "crosspath-2.0.0" = {
      name = "crosspath";
      packageName = "crosspath";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crosspath/-/crosspath-2.0.0.tgz";
        sha512 = "ju88BYCQ2uvjO2bR+SsgLSTwTSctU+6Vp2ePbKPgSCZyy4MWZxYsT738DlKVRE5utUjobjPRm1MkTYKJxCmpTA==";
      };
    };
    "fast-glob-3.2.11" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.2.11.tgz";
        sha512 = "xrO3+1bxSo3ZVHAnqzyuewYT6aMFHRAd4Kcs92MAonjwQZLsK9d0SF1IyQ3k5PoirxTW0Oe/RqFgMQ6TcNE5Ew==";
      };
    };
    "fastq-1.13.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.13.0.tgz";
        sha512 = "YpkpUnK8od0o1hmeSc7UUs/eB/vIPWJYjKck2QKIzAf71Vm1AAQ3EbuZB3g2JIy+pg+ERD0vqI79KyZiB2e2Nw==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "frida-compile-11.1.0" = {
      name = "frida-compile";
      packageName = "frida-compile";
      version = "11.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/frida-compile/-/frida-compile-11.1.0.tgz";
        sha512 = "7/ZguLPlZwBCjNJja2ranAJAW2o1dk4H/mbaYDppsgFwKdUcApHTtHnVYSZQ3YnRUPpapNRjcOePddWP6JqSJw==";
      };
    };
    "frida-fs-5.2.0" = {
      name = "frida-fs";
      packageName = "frida-fs";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/frida-fs/-/frida-fs-5.2.0.tgz";
        sha512 = "xnqE4e1VkMsMyrISCbUayp54ugzZ4mcfcn8N95i2nSMrpjrWxvRx3QMc6N10iXG1is5C2sQzQ6r5eaWUe+Ro0w==";
      };
    };
    "frida-remote-stream-6.0.1" = {
      name = "frida-remote-stream";
      packageName = "frida-remote-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/frida-remote-stream/-/frida-remote-stream-6.0.1.tgz";
        sha512 = "d6ZpZ4Y2g1qDVcV/IThSiwkRJPc4yD88IC/MV0m2+36gIAkS6fuVda2BS5WwKhmd6lo66ZUVNNvcNV+/CatULA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "http-parser-js-0.5.8" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.8.tgz";
        sha512 = "SGeBX54F94Wgu5RH3X5jsDtf4eHyRogWX1XGT3b4HuW3tQPM4AaBzoUji/4AAJNXCEOWZ5O0DgZmJw1947gD5Q==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-core-module-2.9.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz";
        sha512 = "+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.5" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.5.tgz";
        sha512 = "DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "querystring-0.2.1" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.1.tgz";
        sha512 = "wkvS7mL/JMugcup3/rMitHmd9ecIGd2lhFhK9N3UUQ450h66d1r3Y9nvXzQAW1Lq+wyx61k/1pfKS5KuKiyEbg==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "reserved-words-0.1.2" = {
      name = "reserved-words";
      packageName = "reserved-words";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/reserved-words/-/reserved-words-0.1.2.tgz";
        sha512 = "0S5SrIUJ9LfpbVl4Yzij6VipUdafHrOTzvmfazSw/jeZrZtQK303OPZW+obtkaw7jQlTQppy0UvZWm9872PbRw==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "rxjs-7.5.5" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.5.5.tgz";
        sha512 = "sy+H0pQofO95VDmFLzyaw9xNJU4KTRSwQIGM6+iG3SypAtCiLDzpeG8sJrNCWn2Up9km+KhkvTdbkrdy+yzZdw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sjcl-1.0.8" = {
      name = "sjcl";
      packageName = "sjcl";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sjcl/-/sjcl-1.0.8.tgz";
        sha512 = "LzIjEQ0S0DpIgnxMEayM1rq9aGwGRG4OnZhCdjx7glTaJtf4zRfpg87ImfjSJjoW9vKpagd82McDOwbRT5kQKQ==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "terser-5.14.2" = {
      name = "terser";
      packageName = "terser";
      version = "5.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.14.2.tgz";
        sha512 = "oL0rGeM/WFQCUd0y2QrWxYnq7tfSuKBiqTjRPWrRgB46WD/kiwHwF8T23z78H6Q6kGCuuHcPB+KULHRdxvVGQA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "typed-emitter-2.1.0" = {
      name = "typed-emitter";
      packageName = "typed-emitter";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-emitter/-/typed-emitter-2.1.0.tgz";
        sha512 = "g/KzbYKbH5C2vPkaXGu8DJlHrGKHLsM25Zg9WuC9pMGfuvT+X25tZQWo5fK1BjBm8+UrVE9LDCvaY0CQk+fXDA==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
  };
  args = {
    name = "fs-agent";
    packageName = "fs-agent";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@frida/assert-3.0.2"
      sources."@frida/base64-js-2.0.3"
      sources."@frida/buffer-7.0.4"
      sources."@frida/diagnostics_channel-1.0.0"
      sources."@frida/events-4.0.3"
      sources."@frida/http-4.0.1"
      sources."@frida/http-parser-js-1.0.0"
      sources."@frida/https-1.0.0"
      sources."@frida/ieee754-2.0.2"
      sources."@frida/net-4.0.0"
      sources."@frida/os-1.0.2"
      sources."@frida/path-2.0.2"
      sources."@frida/process-1.1.1"
      sources."@frida/punycode-3.0.0"
      sources."@frida/querystring-1.0.0"
      sources."@frida/readable-stream-4.1.3"
      sources."@frida/stream-1.0.1"
      sources."@frida/string_decoder-2.0.0"
      sources."@frida/timers-3.0.0"
      sources."@frida/tty-1.0.0"
      sources."@frida/url-1.0.1"
      sources."@frida/util-1.0.3"
      sources."@frida/vm-2.0.0"
      sources."@jridgewell/gen-mapping-0.3.2"
      sources."@jridgewell/resolve-uri-3.0.8"
      sources."@jridgewell/set-array-1.1.2"
      sources."@jridgewell/source-map-0.3.2"
      sources."@jridgewell/sourcemap-codec-1.4.14"
      sources."@jridgewell/trace-mapping-0.3.14"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@types/frida-gum-18.0.0"
      sources."@types/node-17.0.45"
      sources."acorn-8.7.1"
      sources."base64-js-1.5.1"
      sources."braces-3.0.2"
      sources."buffer-from-1.1.2"
      sources."commander-9.3.0"
      sources."crosspath-2.0.0"
      sources."fast-glob-3.2.11"
      sources."fastq-1.13.0"
      sources."fill-range-7.0.1"
      sources."frida-compile-11.1.0"
      sources."frida-fs-5.2.0"
      sources."frida-remote-stream-6.0.1"
      sources."function-bind-1.1.1"
      sources."glob-parent-5.1.2"
      sources."has-1.0.3"
      sources."http-parser-js-0.5.8"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."is-core-module-2.9.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."merge2-1.4.1"
      sources."micromatch-4.0.5"
      sources."path-parse-1.0.7"
      sources."picomatch-2.3.1"
      sources."punycode-2.1.1"
      sources."querystring-0.2.1"
      sources."queue-microtask-1.2.3"
      sources."readable-stream-3.6.0"
      sources."reserved-words-0.1.2"
      sources."resolve-1.22.1"
      sources."reusify-1.0.4"
      sources."run-parallel-1.2.0"
      sources."rxjs-7.5.5"
      sources."safe-buffer-5.2.1"
      sources."sjcl-1.0.8"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.21"
      sources."string_decoder-1.3.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      (sources."terser-5.14.2" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."to-regex-range-5.0.1"
      sources."tslib-2.4.0"
      sources."typed-emitter-2.1.0"
      sources."util-deprecate-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Agent used by frida-ls and friends";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
